apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podtato-head-monitor
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      app: podtato-head
  endpoints:
  - port: http
    interval: 10s
    path: /metrics
    scheme: http
    targetPort: 9000