apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
spec:
  selector:
    matchLabels:
      app: podtato-head
  endpoints:
  - port: http
    path: /metrics
    targetPort: 9000